module.exports = {
	root: true,
	env: {
		browser: true,
		commonjs: true,
		es6: true,
		es2017: true,
		es2020: true,
		node: true,
	},
	extends: ['eslint:recommended'],
	plugins: ['unused-imports'],
	parserOptions: {
		ecmaVersion: 2018,
		sourceType: 'module',
	},
	rules: {
		'no-trailing-spaces': 'error',
		'no-constant-binary-expression': 'error',
		'no-implicit-coercion': 'error',
		'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
		'no-nested-ternary': 'error',
		'no-underscore-dangle': ['error', { allowAfterThis: true }],
		'no-void': 'error',
		semi: 'error',
		'new-parens': 'error',
		'no-unused-vars': 'off',
		'unused-imports/no-unused-imports': 'error',
		'unused-imports/no-unused-vars': [
			'error',
			{
				vars: 'all',
				varsIgnorePattern: '^_',
				args: 'after-used',
				argsIgnorePattern: '^_',
				ignoreRestSiblings: true,
			},
		],
		'sort-imports': ['error'],
	},
};
